# Generated by Django 4.2 on 2023-05-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_generate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homecustom',
            old_name='caption',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='homecustom',
            old_name='logo',
            new_name='icon',
        ),
        migrations.AlterField(
            model_name='homecustom',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
